spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:9999"
  profiles:
    active: k8s.local

grafana:
  otlp:
    cloud:
      zone: aps1-az1, aps1-az3
      instance-id: 1682323
      api-key: ${GRAFANA_AUTH_TOKEN}