spring:
  application:
    name: api-gateway

#  config:
#    import:
#      - "optional:configserver:http://localhost:9999"
#      - optional:vault://
#
#    cloud:
#      vault:
#        host: localhost
#        port: 8200
#        scheme: http
#        token: hvs.IB7RvtNwphgLco9dZA3icKf7
#
#        kv:
#          enabled: true
#          backend: kv
#          default-context: credentials
#          default-key: application
#
#      gateway:
#        routes:
#          - id: auth-service
#            uri: lb://AUTH-SERVICE
#            predicates:
#              - Path=/api/auth/**
#
#            filters:
#              - name: RequestRateLimiter
#
#                args:
#                  key-resolver: "#{@ipKeyResolver}"
#
#                  redis-rate-limiter.replenishRate: 5
#
#                  redis-rate-limiter.burstCapacity: 10
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          secret-key: ${jwt.secret}
#

#  profiles:
#    active: k8s.local