receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheusremotewrite:
    endpoint: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    headers:
      Authorization: "Basic MzI4ODg3MDpnbGNfZXlKdklqb2lNVGd3TXpRMk1DSXNJbTRpT2lKemRHRmpheTB4TmpneU16SXpMVzkwYkhBdGQzSnBkR1V0WVhWMGFDMTBiMnRsYmlJc0ltc2lPaUl3Y0VvNFNUWllNelZ6T0ZGMlZqRTBZakpXVUZOd1J6VWlMQ0p0SWpwN0luSWlPaUp3Y205a0xXRndMWE52ZFhSb0xURWlmWDA9"

  otlphttp/loki:
    endpoint: https://logs-prod-028.grafana.net/otlp
    headers:
      Authorization: "Basic MTY0MDExMDpnbGNfZXlKdklqb2lNVGd3TXpRMk1DSXNJbTRpT2lKemRHRmpheTB4TmpneU16SXpMVzkwYkhBdGQzSnBkR1V0WVhWMGFDMTBiMnRsYmlJc0ltc2lPaUl3Y0VvNFNUWllNelZ6T0ZGMlZqRTBZakpXVUZOd1J6VWlMQ0p0SWpwN0luSWlPaUp3Y205a0xXRndMWE52ZFhSb0xURWlmWDA9"

  otlp/tempo:
    endpoint: tempo-prod-19-prod-ap-south-1.grafana.net:443
    tls:
      insecure: false
    headers:
      Authorization: "Basic MTYzNDQxMTpnbGNfZXlKdklqb2lNVGd3TXpRMk1DSXNJbTRpT2lKemRHRmpheTB4TmpneU16SXpMVzkwYkhBdGQzSnBkR1V0WVhWMGFDMTBiMnRsYmlJc0ltc2lPaUl3Y0VvNFNUWllNelZ6T0ZGMlZqRTBZakpXVUZOd1J6VWlMQ0p0SWpwN0luSWlPaUp3Y205a0xXRndMWE52ZFhSb0xURWlmWDA9"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]